// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Tauri command wrapper — see [`build_graph`].
 */
async loadGraph(path: string, limit: number | null) : Promise<Result<GraphData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_graph", { path, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: return the full message + real changed-file tree + diff hunks
 * for a single commit. Diffs the commit tree against its FIRST parent (empty
 * tree for a root commit; first parent for a merge). Read-only.
 */
async commitDetail(path: string, sha: string) : Promise<Result<CommitDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_detail", { path, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSnapshot(path: string) : Promise<Result<Snapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_snapshot", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSnapshots(path: string) : Promise<Result<Snapshot[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snapshots", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async undoLast(path: string) : Promise<Result<UndoResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_last", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list local branches (+ ahead/behind vs upstream), remote
 * branches, and tags, plus the current branch shorthand. Read-only (git2).
 */
async listRefs(path: string) : Promise<Result<RefList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_refs", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a branch; when `checkout` is true, also switch to it (`git switch -c`).
 * `start_point` is an optional commit-ish; defaults to HEAD when omitted.
 * JS call: `invoke("create_branch", { path, name, startPoint?, checkout? })`.
 */
async createBranch(path: string, name: string, startPoint: string | null, checkout: boolean | null) : Promise<WriteResult> {
    return await TAURI_INVOKE("create_branch", { path, name, startPoint, checkout });
},
/**
 * Switch HEAD to an existing branch. Uses `git switch` (never touches
 * pathspecs, so no branch/path ambiguity). A dirty tree that would be
 * clobbered is surfaced as `ok:false` with git's message — we never force.
 * JS call: `invoke("checkout", { path, name })`.
 */
async checkout(path: string, name: string) : Promise<WriteResult> {
    return await TAURI_INVOKE("checkout", { path, name });
},
/**
 * Delete a branch. Refuses the current branch. `force=false` uses `git branch
 * -d` (refuses an unmerged branch -> surfaced as `ok:false`); `force=true` uses
 * `-D`. The deleted tip sha is included in the success message since M2a Undo
 * restores HEAD only (full-repo ref restore comes later).
 * JS call: `invoke("delete_branch", { path, name, force })`.
 */
async deleteBranch(path: string, name: string, force: boolean) : Promise<WriteResult> {
    return await TAURI_INVOKE("delete_branch", { path, name, force });
},
/**
 * Rename a branch. Uses `git branch -m` (NOT `-M`), so it refuses to clobber an
 * existing target. Works on the current branch (git updates the HEAD symref).
 * JS call: `invoke("rename_branch", { path, from, to })`.
 */
async renameBranch(path: string, from: string, to: string) : Promise<WriteResult> {
    return await TAURI_INVOKE("rename_branch", { path, from, to });
},
/**
 * Tauri command: full working-tree/index status for the pinned "Uncommitted
 * changes" row + staging panel. Read-only (git2).
 * JS: `invoke("workdir_status", { path })`.
 */
async workdirStatus(path: string) : Promise<Result<WorkdirStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workdir_status", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: the real diff for ONE file, either the staged side (index
 * vs HEAD) or the unstaged side (workdir vs index). Reuses `model::FileChange`
 * verbatim so the frontend's diff viewer can share `Detail.svelte`'s markup.
 * JS: `invoke("workdir_file_diff", { path, file, staged })`.
 */
async workdirFileDiff(path: string, file: string, staged: boolean) : Promise<Result<FileChange, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workdir_file_diff", { path, file, staged }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stage one file's full state (new/modified/deleted) with a single explicit
 * pathspec. JS: `invoke("stage_file", { path, file })`.
 */
async stageFile(path: string, file: string) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("stage_file", { path, file });
},
/**
 * Unstage one file (`git restore --staged`), leaving the working tree as-is.
 * JS: `invoke("unstage_file", { path, file })`.
 */
async unstageFile(path: string, file: string) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("unstage_file", { path, file });
},
/**
 * Stage every unstaged/untracked path (`git add -A`).
 * JS: `invoke("stage_all", { path })`.
 */
async stageAll(path: string) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("stage_all", { path });
},
/**
 * Discard unstaged changes to one file. Destructive: this is the ONE gap the
 * Safety-Manager ref mechanism cannot cover (see doc comment), so it ALWAYS
 * writes a content backup first, then mutates. `untracked=false` restores a
 * tracked file's content to what's in the index (`git restore --worktree`);
 * `untracked=true` removes an untracked file (`git clean -f`). An UNSTAGED
 * RENAME (`old_path` set, `untracked=false`) is a special case handled by
 * [`discard_unstaged_rename`] — see its doc comment for why the plain path
 * below can't handle it (it always finds zero deltas and refuses with "No
 * unstaged changes to discard", even though the status view correctly shows
 * a rename). The caller (frontend controller) is responsible for a
 * typed-confirm gate before this is ever invoked — this command itself does
 * not prompt.
 * JS: `invoke("discard_file", { path, file, untracked })`.
 */
async discardFile(path: string, file: string, untracked: boolean) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("discard_file", { path, file, untracked });
},
/**
 * Create a commit from the current index, or amend the previous one.
 * Snapshots FIRST (amend rewrites the previous commit's sha — history-
 * mutating). `!amend && message` empty/whitespace-only -> refused before any
 * snapshot. `amend && message` empty/`None` -> `--amend --no-edit` (keeps the
 * prior message). `amend && message` non-empty -> `--amend -m <message>`.
 * Otherwise -> `-m <message>`. Nothing preemptively re-checks "is anything
 * staged" — a refusal ("nothing to commit") surfaces verbatim from git.
 * JS: `invoke("commit", { path, message, amend })`.
 */
async commit(path: string, message: string | null, amend: boolean | null) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("commit", { path, message, amend });
},
/**
 * Tauri command: list stash entries, newest first, via
 * `git stash list --format=%gd\x01%H\x01%gs` (libgit2 has no stash API).
 * JS: `invoke("stash_list", { path })`.
 */
async stashList(path: string) : Promise<Result<StashEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_list", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * `git stash push [-u] [-m <message>]`. Snapshots FIRST.
 * JS: `invoke("stash_save", { path, message, includeUntracked })`.
 */
async stashSave(path: string, message: string | null, includeUntracked: boolean | null) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("stash_save", { path, message, includeUntracked });
},
/**
 * `git stash apply stash@{index}`. On a conflict, git never drops the stash
 * entry — `stash_list` will still show it. `expected_sha` is an OPTIONAL
 * sanity check (see [`check_stash_identity`]): pass the `StashEntry.sha`
 * last fetched for this index, and the op refuses instead of silently
 * acting on a different entry if the stash list changed since (e.g. an
 * external `git stash` command). JS: `invoke("stash_apply", { path, index,
 * expectedSha })`.
 */
async stashApply(path: string, index: number, expectedSha: string | null) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("stash_apply", { path, index, expectedSha });
},
/**
 * `git stash pop stash@{index}`. On a conflict, git leaves the stash entry in
 * place (only a clean pop drops it). `expected_sha`: see [`stash_apply`].
 * JS: `invoke("stash_pop", { path, index, expectedSha })`.
 */
async stashPop(path: string, index: number, expectedSha: string | null) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("stash_pop", { path, index, expectedSha });
},
/**
 * `git stash drop stash@{index}`. Snapshots HEAD first like every other
 * stash op (see doc comment), but — unlike that HEAD snapshot — a stash
 * drop's own content is NOT reachable through `safety::undo()`/global Undo
 * at all (`snapshot()` only ever tracks `refs/heads/*`, never `refs/stash`),
 * so this pins the STASH's own commit under a dedicated ref
 * ([`pin_dropped_stash`]) BEFORE ever running `git stash drop`, and reports
 * that pin honestly in `dropped_stash_ref`/`message` instead of implying
 * the generic Undo button restores it. `expected_sha`: see [`stash_apply`].
 * JS: `invoke("stash_drop", { path, index, expectedSha })`.
 */
async stashDrop(path: string, index: number, expectedSha: string | null) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("stash_drop", { path, index, expectedSha });
},
/**
 * Undo a `stash_apply`/`stash_pop` by re-stashing whatever is now dirty,
 * restoring a clean working tree via a real `git stash push -u`. Wired into
 * the global Undo (⌘Z) flow by the frontend specifically for these two ops
 * (the frontend knows locally which mutation just ran; see the workdir
 * controller) — NOT a change to `safety::undo()`'s own dirty-tree guard,
 * which keeps refusing on every OTHER kind of dirty state exactly as
 * before.
 * 
 * HONEST about what this does and doesn't restore: nothing at the ref level
 * (HEAD/branches) ever moved, so there is nothing to rewind there. This is
 * NOT a byte-for-byte replay of the exact stash that was applied/popped —
 * apply's original entry is left untouched (this push creates an ADDITIONAL
 * entry alongside it); pop's original entry was already dropped on a clean
 * pop (this push recreates its CONTENT under a brand-new stash commit/
 * timestamp, not the same object). The practical guarantee is the same one
 * Undo makes everywhere else: the working tree ends up clean again and
 * nothing is lost. Refuses if conflicted paths remain from a stash conflict
 * — that is `stash_conflict_abort`/`stash_conflict_continue`'s job (a stash
 * conflict is never a "just re-stash it" situation).
 * JS: `invoke("stash_undo_apply", { path })`.
 */
async stashUndoApply(path: string) : Promise<WorkdirResult> {
    return await TAURI_INVOKE("stash_undo_apply", { path });
},
/**
 * Abort a stash-apply/pop conflict left by `apply_or_pop`. `git stash
 * apply`/`pop` has no native `--abort` of its own (unlike merge/rebase/
 * cherry-pick), so this uses the mechanism the finding calls for: reset the
 * working tree AND index back to the pre-attempt state via the safety
 * snapshot's own backup ref (`git reset --hard <backup_ref>`) sealed by
 * `apply_or_pop` right before it ran. The stash entry itself is UNTOUCHED
 * either way (apply never removes it; a conflicted pop never drops it
 * either — empirically verified, see module doc comment), so nothing about
 * the stash list changes. CAVEAT (documented, not hidden): `backup_ref` only
 * ever pins HEAD's COMMIT, not the working tree — if the tree already had
 * OTHER uncommitted changes before this apply/pop was attempted, this reset
 * discards those too, same limitation `safety::undo()`'s own dirty-tree
 * guard exists to avoid elsewhere; there is no git-level way around that for
 * an op that (unlike merge/rebase) is explicitly designed to run on top of a
 * dirty tree.
 * JS: `invoke("stash_conflict_abort", { path })`.
 */
async stashConflictAbort(path: string) : Promise<StashResolveResult> {
    return await TAURI_INVOKE("stash_conflict_abort", { path });
},
/**
 * Finish a stash-apply/pop conflict after the user resolved every file (via
 * the shared Resolver's per-file `resolve_conflict_file`, allowlisted for
 * `"stash"` — see `conflict.rs`) and staged the result. Refuses (reporting
 * `state:"conflict"` again, same convention as `git_merge::classify`/
 * `git_rebase`'s classify) if unmerged paths remain. For `apply`, nothing
 * further is needed — the stash entry was never touched. For `pop`, the
 * whole point of popping was to remove the stash entry, but a CONFLICTED
 * pop never drops it (empirically verified, see module doc comment) — so
 * only NOW, once the user has actually kept the resolution, do we drop it,
 * re-verifying its identity first (in case the stash list changed during
 * the conflict) rather than blindly dropping whatever now sits at that
 * index.
 * JS: `invoke("stash_conflict_continue", { path })`.
 */
async stashConflictContinue(path: string) : Promise<StashResolveResult> {
    return await TAURI_INVOKE("stash_conflict_continue", { path });
},
/**
 * Update remote-tracking refs. `remote` fetches just that one remote;
 * omitted, it fetches every configured remote (`--all`). Always `--prune`s
 * stale remote-tracking branches that no longer exist on the remote.
 * JS call: `invoke("fetch", { path, remote? })`.
 */
async fetch(path: string, remote: string | null) : Promise<RemoteResult> {
    return await TAURI_INVOKE("fetch", { path, remote });
},
/**
 * Fast-forward the current branch to its upstream (`git pull --ff-only`).
 * Refuses (git's own message) rather than merging/rebasing on divergence —
 * see module doc for why.
 * JS call: `invoke("pull", { path })`.
 */
async pull(path: string) : Promise<RemoteResult> {
    return await TAURI_INVOKE("pull", { path });
},
/**
 * Push the current branch. Publishes to "origin" with `--set-upstream` when
 * it has no configured upstream yet; otherwise a plain `git push`. Never
 * force-pushes — a non-fast-forward rejection surfaces git's own message.
 * JS call: `invoke("push", { path })`.
 */
async push(path: string) : Promise<RemoteResult> {
    return await TAURI_INVOKE("push", { path });
},
/**
 * Report the in-progress operation and the conflicted files (with all three
 * merge stages). Read-only. JS: `invoke("conflict_status", { path })`.
 */
async conflictStatus(path: string) : Promise<Result<ConflictStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conflict_status", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve one conflicted file by taking the whole `ours` or `theirs` side, then
 * staging it. Returns how many files are still unmerged so the UI can flip to
 * "Continue" when it reaches 0. JS: `invoke("resolve_conflict_file", { path,
 * file, side })` where `side` is `"ours"` or `"theirs"`.
 * 
 * No snapshot here — see the module doc: the enclosing op was snapshotted and
 * its `--abort` restores everything.
 */
async resolveConflictFile(path: string, file: string, side: string) : Promise<ResolveResult> {
    return await TAURI_INVOKE("resolve_conflict_file", { path, file, side });
},
/**
 * Cherry-pick `sha` onto the current branch (HEAD). Snapshots FIRST, then runs
 * `git cherry-pick [-x] --no-edit --end-of-options <sha>`. `record_origin`
 * (the `-x` toggle) appends "(cherry picked from commit …)" to the message.
 * 
 * A dirty working tree makes git refuse the pick — that surfaces as
 * `state:"error"` with git's own message; we never force. On a conflict this
 * resolves to `state:"conflict"` (repo left mid-pick for the resolver), NOT a
 * failure.
 * 
 * JS: `invoke("cherry_pick", { path, sha, recordOrigin? })`.
 */
async cherryPick(path: string, sha: string, recordOrigin: boolean | null) : Promise<PickResult> {
    return await TAURI_INVOKE("cherry_pick", { path, sha, recordOrigin });
},
/**
 * Continue an in-progress cherry-pick after the user resolved the conflict
 * (files were `git add`ed by the resolver). Runs `git cherry-pick --continue`
 * with `GIT_EDITOR=true` so it commits the resolution non-interactively.
 * 
 * Re-classifies the outcome: `clean` on success, `conflict` again if conflicts
 * remain unresolved, or `empty` if the resolution left no net change.
 * 
 * JS: `invoke("cherry_pick_continue", { path })`.
 */
async cherryPickContinue(path: string) : Promise<PickResult> {
    return await TAURI_INVOKE("cherry_pick_continue", { path });
},
/**
 * Abort an in-progress cherry-pick: `git cherry-pick --abort` restores the
 * pre-pick state. This is the escape hatch — it must ALWAYS be able to run, so
 * it deliberately does NOT take a snapshot (a snapshot failure must never block
 * the user's way out). Idempotent: "nothing in progress" is a benign success.
 * 
 * JS: `invoke("cherry_pick_abort", { path })`.
 */
async cherryPickAbort(path: string) : Promise<PickResult> {
    return await TAURI_INVOKE("cherry_pick_abort", { path });
},
/**
 * Merge `sha` into the current branch (HEAD). Snapshots FIRST, then runs
 * `git merge --no-edit --end-of-options <sha>`.
 * 
 * A dirty working tree makes git refuse the merge — that surfaces as
 * `state:"error"` with git's own message; we never force. On a conflict this
 * resolves to `state:"conflict"` (repo left mid-merge for the resolver), NOT
 * a failure.
 * 
 * JS: `invoke("merge_start", { path, sha })`.
 */
async mergeStart(path: string, sha: string) : Promise<MergeResult> {
    return await TAURI_INVOKE("merge_start", { path, sha });
},
/**
 * Continue an in-progress merge after the user resolved the conflict (files
 * were `git add`ed by the resolver). Runs `git merge --continue` with
 * `GIT_EDITOR=true` so it commits the resolution non-interactively.
 * 
 * Re-classifies the outcome: `clean` on success, `conflict` again if
 * conflicts remain unresolved.
 * 
 * JS: `invoke("merge_continue", { path })`.
 */
async mergeContinue(path: string) : Promise<MergeResult> {
    return await TAURI_INVOKE("merge_continue", { path });
},
/**
 * Abort an in-progress merge: `git merge --abort` restores the pre-merge
 * state. This is the escape hatch — it must ALWAYS be able to run, so it
 * deliberately does NOT take a snapshot (a snapshot failure must never block
 * the user's way out). Idempotent: "nothing in progress" is a benign success.
 * 
 * JS: `invoke("merge_abort", { path })`.
 */
async mergeAbort(path: string) : Promise<MergeResult> {
    return await TAURI_INVOKE("merge_abort", { path });
},
/**
 * Rebase the current branch onto `onto`. Snapshots FIRST, then runs
 * `git rebase --end-of-options <onto>` (linear only — no `-i`; a
 * `GIT_SEQUENCE_EDITOR=true`/`GIT_EDITOR=true` non-interactive editor is set
 * so nothing can block a headless app).
 * 
 * A dirty working tree makes git refuse the rebase — that surfaces as
 * `state:"error"` with git's own message; we never force. On a conflict this
 * resolves to `state:"conflict"` (repo left mid-rebase for the resolver), NOT
 * a failure.
 * 
 * JS: `invoke("rebase_start", { path, onto })`.
 */
async rebaseStart(path: string, onto: string) : Promise<RebaseResult> {
    return await TAURI_INVOKE("rebase_start", { path, onto });
},
/**
 * Continue an in-progress rebase after the user resolved the conflict (files
 * were `git add`ed by the resolver). Runs `git rebase --continue` with
 * `GIT_EDITOR=true`/`GIT_SEQUENCE_EDITOR=true` so it commits the resolution
 * non-interactively.
 * 
 * Re-classifies the outcome: `clean` once the whole sequence finishes,
 * `conflict` again if THIS commit is still unresolved, or — critically —
 * `conflict` again if resolving this commit landed on the NEXT conflicting
 * commit in the sequence (empirically verified, see tests/rebase.rs).
 * 
 * JS: `invoke("rebase_continue", { path })`.
 */
async rebaseContinue(path: string) : Promise<RebaseResult> {
    return await TAURI_INVOKE("rebase_continue", { path });
},
/**
 * Skip the commit the rebase is currently stopped on — DROPS it from the
 * resulting history entirely (distinct from Abort/Continue; this is the one
 * op where mid-sequence skip is meaningful). Runs `git rebase --skip` with
 * the same non-interactive editor guards.
 * 
 * Re-classifies the outcome exactly like `rebase_continue`: `clean` once the
 * sequence finishes, or `conflict` again if skipping landed on the next
 * conflicting commit (empirically verified, see tests/rebase.rs).
 * 
 * JS: `invoke("rebase_skip", { path })`.
 */
async rebaseSkip(path: string) : Promise<RebaseResult> {
    return await TAURI_INVOKE("rebase_skip", { path });
},
/**
 * Abort an in-progress rebase: `git rebase --abort` restores the pre-rebase
 * state. This is the escape hatch — it must ALWAYS be able to run, so it
 * deliberately does NOT take a snapshot (a snapshot failure must never block
 * the user's way out). Idempotent: "nothing in progress" is a benign success.
 * 
 * JS: `invoke("rebase_abort", { path })`.
 */
async rebaseAbort(path: string) : Promise<RebaseResult> {
    return await TAURI_INVOKE("rebase_abort", { path });
},
/**
 * Start a bisect between a known-bad and one-or-more known-good commits.
 * Snapshots FIRST. JS: invoke("bisect_start", { path, bad, good: [sha,…] }).
 */
async bisectStart(path: string, bad: string, good: string[]) : Promise<BisectStatus> {
    return await TAURI_INVOKE("bisect_start", { path, bad, good });
},
/**
 * Mark the checked-out midpoint (HEAD) good/bad/skip. No snapshot.
 * JS: invoke("bisect_mark", { path, term }) where term ∈ {good,bad,skip}.
 */
async bisectMark(path: string, term: string) : Promise<BisectStatus> {
    return await TAURI_INVOKE("bisect_mark", { path, term });
},
/**
 * Read-only bisect status (also serves as `bisect log`). Never mutates.
 * JS: invoke("bisect_status", { path }).
 */
async bisectStatus(path: string) : Promise<BisectStatus> {
    return await TAURI_INVOKE("bisect_status", { path });
},
/**
 * End the bisect and restore the original HEAD/branch. Escape hatch: NO
 * snapshot; idempotent. JS: invoke("bisect_reset", { path }).
 */
async bisectReset(path: string) : Promise<BisectStatus> {
    return await TAURI_INVOKE("bisect_reset", { path });
},
/**
 * Read HEAD's reflog, newest first. Read-only (git2).
 * 
 * JS: `commands.reflog(path)` -> `Result<ReflogEntry[], string>`.
 */
async reflog(path: string) : Promise<Result<ReflogEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reflog", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore HEAD (and the current branch, if attached) to the commit recorded
 * at `HEAD@{index}`. A plain-struct result (like `safety::undo`) — failure is
 * `ok:false` + a message, never a JS rejection, so the UI can always show why.
 * 
 * Invariants (identical to `safety::undo`):
 * 1. Refuses on a dirty working tree (a `reset --hard` would silently
 * discard uncommitted work) — never forced.
 * 2. Snapshots the CURRENT state FIRST, so this restore is itself undoable
 * via the normal global Undo afterward.
 * 3. Re-validates `index` against a FRESH reflog read (the reflog can
 * change between the list render and the restore click — a stale index
 * must never silently land on the wrong commit).
 * 
 * JS: `commands.reflogRestore(path, index)` -> `UndoResult`.
 */
async reflogRestore(path: string, index: number) : Promise<UndoResult> {
    return await TAURI_INVOKE("reflog_restore", { path, index });
},
/**
 * JS: `invoke("rerere_status", { path })`.
 */
async rerereStatus(path: string) : Promise<Result<RerereStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rerere_status", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle `rerere.enabled` for THIS repository only (never `--global`). JS:
 * `invoke("rerere_set_enabled", { path, enabled })`.
 */
async rerereSetEnabled(path: string, enabled: boolean) : Promise<WriteResult> {
    return await TAURI_INVOKE("rerere_set_enabled", { path, enabled });
},
/**
 * Resolve `rev` (sha / short-sha / branch / tag / `HEAD~2` / `HEAD^{tree}` /
 * … — ordinary git rev syntax) and report a detail view of whatever object it
 * names. JS: `invoke("plumbing_inspect", { path, rev })`.
 */
async plumbingInspect(path: string, rev: string) : Promise<Result<PlumbingObject, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plumbing_inspect", { path, rev }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read-only preview shown before the user commits to running filter-repo.
 */
async filterRepoPreview(path: string, paths: string[], invert: boolean) : Promise<Result<FilterRepoPreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("filter_repo_preview", { path, paths, invert }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run `git filter-repo` against the given scope, after a mandatory verified
 * backup. Plain-struct failure model — see module docs.
 */
async filterRepoRun(path: string, paths: string[], invert: boolean) : Promise<FilterRepoResult> {
    return await TAURI_INVOKE("filter_repo_run", { path, paths, invert });
},
/**
 * Restore every ref namespace a previous backup captured. Pins any
 * at-risk CURRENT tip under `refs/gitgui/deleted/*` first (data-safety,
 * mirrors safety::undo's pre-move pinning) so nothing is silently orphaned
 * even if the user regrets the restore itself.
 */
async filterRepoRestore(path: string, backupId: string) : Promise<FilterRepoResult> {
    return await TAURI_INVOKE("filter_repo_restore", { path, backupId });
},
/**
 * List available backups (survives app restarts — reads the on-disk log).
 */
async filterRepoListBackups(path: string) : Promise<Result<FilterRepoBackupInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("filter_repo_list_backups", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * JS: `commands.getGitIdentity(path)` -> `Promise<Result<GitIdentity,string>>`.
 * Fails only if `path` isn't a git repository at all (used by the setup
 * wizard as its directory-validation step, doubling as the identity check).
 */
async getGitIdentity(path: string) : Promise<Result<GitIdentity, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_git_identity", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * JS: `commands.setGitIdentity(path, name, email)` -> `Promise<WriteResult>`
 * (never rejects; `ok:false` + message on failure). Writes ONLY this repo's
 * local config (never `--global`). Non-destructive metadata, no ref/history
 * touched, so — per the safety-model convention used by rerere_set_enabled —
 * this does NOT take a Safety Manager snapshot first.
 */
async setGitIdentity(path: string, name: string, email: string) : Promise<WriteResult> {
    return await TAURI_INVOKE("set_git_identity", { path, name, email });
},
async watchRepo(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("watch_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unwatchRepo() : Promise<void> {
    await TAURI_INVOKE("unwatch_repo");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BisectStatus = { ok: boolean; inProgress: boolean; current: CommitInfo | null; badRef: string | null; goodRefs: string[]; remainingRevs: number; estSteps: number; firstBad: CommitInfo | null; log: string[]; message: string; backupRef: string | null }
export type BlobObject = { sha: string; size: number; isBinary: boolean; 
/**
 * UTF-8-lossy content capped to [`CAP_LINES`] lines; `None` for a binary
 * blob (only `size` is reported).
 */
content: string | null; truncated: boolean }
/**
 * Full payload for the M1 commit detail panel: message + real diff tree.
 */
export type CommitDetail = { sha: string; shortSha: string; subject: string; body: string; message: string; additions: number; deletions: number; filesChanged: number; truncated: boolean; fileTree: FileChange[] }
export type CommitInfo = { sha: string; subject: string }
/**
 * Per-commit metadata (one entry per row, row = index).
 */
export type CommitMeta = { sha: string; subject: string; an: Person; cm: Person; refs: RefChip[]; merge: boolean }
export type CommitObject = { sha: string; shortSha: string; author: PlumbingPerson; committer: PlumbingPerson; parents: string[]; tree: string; message: string }
/**
 * One conflicted file, with the three merge stages as text.
 * 
 * `base` = stage 1 (common ancestor), `ours` = stage 2 (HEAD / current branch),
 * `theirs` = stage 3 (the incoming commit — during a cherry-pick, the picked
 * commit). A side that is **absent** (e.g. add/add has no base; delete/modify
 * has no ours or theirs) is the empty string; a **binary** side is the marker
 * `"‹binary›"`. Each side is UTF-8-lossy and capped to [`CAP_LINES`].
 */
export type ConflictFile = { path: string; ours: string; base: string; theirs: string }
/**
 * Result of [`conflict_status`]. `op` is one of
 * `"cherry-pick" | "merge" | "rebase" | "revert" | "stash" | "none"` — see
 * [`detect_op`] for why `"stash"` exists (a `git stash apply`/`pop` conflict
 * leaves `RepositoryState` at `Clean`, unlike every other op here).
 * `in_progress` is true whenever a sequencer op is underway **or** there are
 * unmerged files — so once every file is resolved (`files` empty) but the
 * cherry-pick has not been continued yet, `in_progress` stays true and the
 * UI can offer Continue.
 */
export type ConflictStatus = { inProgress: boolean; op: string; files: ConflictFile[] }
/**
 * One hunk within a file patch. `header` is the `@@ -a,b +c,d @@ ...` line.
 */
export type DiffHunkRow = { header: string; lines: DiffLineRow[] }
/**
 * One line inside a diff hunk. `old_no`/`new_no` are the 1-based line numbers
 * on each side; the added side has `old_no == None`, the deleted side
 * `new_no == None`, context lines carry both. `text` is the raw line content
 * with any trailing CR/LF stripped — the frontend HTML-escapes it.
 */
export type DiffLineRow = { kind: string; oldNo: number | null; newNo: number | null; text: string }
/**
 * One changed file: its status, per-file stats, and hunks. `hunks` is empty
 * for a binary file (`binary == true`) or when the file was capped
 * (`truncated == true`). `old_path` is set only for renames/copies.
 */
export type FileChange = { path: string; oldPath: string | null; status: string; additions: number; deletions: number; binary: boolean; truncated: boolean; lang: string; hunks: DiffHunkRow[] }
/**
 * One backup entry as shown in a "restore from a previous backup" list.
 */
export type FilterRepoBackupInfo = { 
/**
 * Opaque id passed back into `filter_repo_restore`.
 */
id: string; bundlePath: string; ts: number; 
/**
 * Symbolic HEAD ref at backup time ("refs/heads/main"), "" if detached.
 */
headBranch: string; headSha: string; refCount: number; description: string }
/**
 * Read-only preview shown BEFORE the user commits to running filter-repo.
 */
export type FilterRepoPreview = { 
/**
 * Whether the `git-filter-repo` binary is available at all, so the
 * wizard's final confirm step can be disabled/greyed cleanly.
 */
available: boolean; currentBranch: string; totalCommits: number; 
/**
 * `git rev-list --count HEAD -- <paths...>` — how many commits on the
 * current branch touch the requested scope.
 */
touchedCommits: number }
/**
 * Result of `filter_repo_run` / `filter_repo_restore`. Plain struct (never a
 * Rust `Err`) — see module docs on the failure model.
 */
export type FilterRepoResult = { ok: boolean; message: string; backupBundle: string | null; commitsBefore: number | null; commitsAfter: number | null }
export type GitIdentity = { name: string | null; email: string | null; 
/**
 * true only when BOTH name and email are set in this repo's local config.
 */
configured: boolean }
/**
 * The full graph payload. Rows are in reverse-chronological/topological order
 * (child before parent). `lane`/`color`/`merge` are one-per-row.
 * 
 * Edges are stored CSR-style: `gap g` is the band between row g and row g+1;
 * `gapStart[g]..gapStart[g+1]` indexes into `gapTop`/`gapBot`/`gapColor`, each
 * entry a line segment {top lane @row g, bottom lane @row g+1, colour index}.
 */
export type GraphData = { n: number; lane: number[]; color: number[]; merge: number[]; gapStart: number[]; gapTop: number[]; gapBot: number[]; gapColor: number[]; rows: CommitMeta[]; ncol: number; laneCount: number; layoutMs: number; readMs: number }
/**
 * A local branch row for the data-driven sidebar. `ahead`/`behind` are relative
 * to the branch's configured upstream, or `None` when it has no upstream.
 */
export type LocalBranch = { name: string; sha: string; ahead: number | null; behind: number | null }
/**
 * Result of any merge step (initial / continue / abort). Serializes
 * camelCase: `conflictedFiles`, `backupRef`.
 */
export type MergeResult = { ok: boolean; 
/**
 * "clean" | "conflict" | "empty" | "error"
 */
state: string; 
/**
 * Repo-relative paths with unmerged entries — non-empty only when
 * `state == "conflict"`.
 */
conflictedFiles: string[]; message: string; 
/**
 * Pre-op safety snapshot ref (present when we snapshotted before mutating),
 * so the UI can name the snapshot the user can Undo to.
 */
backupRef: string | null }
/**
 * One author/committer identity. `t` is a unix timestamp; the frontend formats it.
 */
export type Person = { n: string; e: string; t: number }
/**
 * Result of any cherry-pick step (initial / continue / abort). Serializes
 * camelCase: `conflictedFiles`, `backupRef`.
 */
export type PickResult = { ok: boolean; 
/**
 * "clean" | "conflict" | "empty" | "error"
 */
state: string; 
/**
 * Repo-relative paths with unmerged entries — non-empty only when
 * `state == "conflict"`.
 */
conflictedFiles: string[]; message: string; 
/**
 * Pre-op safety snapshot ref (present when we snapshotted before mutating),
 * so the UI can name the snapshot the user can Undo to.
 */
backupRef: string | null }
/**
 * Whatever `revparse_single` resolved `rev` to. Internally tagged on `kind`
 * (verified empirically against specta 2.0.0-rc.22 — this generates a clean
 * discriminated TS union, each variant's fields flattened alongside the
 * `kind` tag, e.g. `{ kind: "commit", sha, shortSha, … }`).
 */
export type PlumbingObject = ({ kind: "commit" } & CommitObject) | ({ kind: "tree" } & TreeObject) | ({ kind: "blob" } & BlobObject) | ({ kind: "tag" } & TagObject)
/**
 * One author/tagger/committer identity. `time` is unix seconds.
 */
export type PlumbingPerson = { name: string; email: string; time: number }
/**
 * Result of any rebase step (start / continue / skip / abort). Serializes
 * camelCase: `conflictedFiles`, `backupRef`.
 */
export type RebaseResult = { ok: boolean; 
/**
 * "clean" | "conflict" | "empty" | "error"
 */
state: string; 
/**
 * Repo-relative paths with unmerged entries — non-empty only when
 * `state == "conflict"`.
 */
conflictedFiles: string[]; message: string; 
/**
 * Pre-op safety snapshot ref (present when we snapshotted before mutating),
 * so the UI can name the snapshot the user can Undo to.
 */
backupRef: string | null }
/**
 * A ref chip pointing at a commit. `t` is one of: head | branch | remote | tag.
 */
export type RefChip = { n: string; t: string }
/**
 * Everything the sidebar needs. `head` is the current branch shorthand, or
 * `None` when HEAD is detached or unborn.
 */
export type RefList = { head: string | null; locals: LocalBranch[]; remotes: SimpleRef[]; tags: SimpleRef[] }
/**
 * One HEAD reflog entry, newest first (`index` == the `HEAD@{index}` you'd
 * pass to plain git). `kind` is a best-effort coarse category derived from
 * `message`'s leading word, purely for a nicer icon in the UI — not a
 * guarantee every git reflog message shape is recognized.
 */
export type ReflogEntry = { index: number; sha: string; message: string; kind: string; committerName: string; committerEmail: string; ts: number }
export type RemoteResult = { ok: boolean; message: string; 
/**
 * Pre-op safety snapshot ref — only ever `Some` for `pull` (see module doc).
 */
backupRef: string | null }
/**
 * One historical resolution recorded under `<git-common-dir>/rr-cache/<id>/`.
 * `id` is the cache directory name — a hash of the conflict hunk's content,
 * NOT of the file it came from. `resolved` is true once a `postimage` file
 * exists; false while only a `preimage` exists (conflict seen, never
 * resolved — e.g. an aborted merge).
 * 
 * `path` is deliberately NOT a field here: once a conflict is no longer live,
 * git itself has no mapping from a cache id back to a file path. See
 * [`RererePath`] for the one case a path IS actually derivable.
 */
export type RerereEntry = { id: string; resolved: boolean }
/**
 * A path rerere is tracking for the CURRENTLY in-progress conflict. Only
 * populated while a conflict is live.
 */
export type RererePath = { path: string; resolved: boolean }
/**
 * Result of [`rerere_status`].
 */
export type RerereStatus = { 
/**
 * The EFFECTIVE state: what git will actually do on the next conflict.
 * `configured.unwrap_or(cacheDirPresent)`.
 */
enabled: boolean; 
/**
 * The explicit `rerere.enabled` value git resolves (local/global,
 * whichever wins), or `None` if never set anywhere.
 */
configured: boolean | null; 
/**
 * Whether `<git-common-dir>/rr-cache` exists — the fallback git itself
 * uses when `configured` is `None`.
 */
cacheDirPresent: boolean; 
/**
 * Historical rr-cache entries (hash + resolved-status only).
 */
entries: RerereEntry[]; 
/**
 * True while a merge/cherry-pick/rebase/revert conflict is in progress
 * AND rerere is tracking at least one path for it.
 */
liveConflict: boolean; 
/**
 * Paths for the live conflict; always empty when `live_conflict` is false.
 */
livePaths: RererePath[] }
/**
 * Result of [`resolve_conflict_file`]. `remaining` is the count of files still
 * unmerged after this resolution (0 means the tree is ready to Continue).
 */
export type ResolveResult = { ok: boolean; remaining: number; message: string }
/**
 * A remote-tracking branch or a tag: just a name and the commit it resolves to.
 */
export type SimpleRef = { name: string; sha: string }
/**
 * One backup snapshot, as shown in the ribbon / Snapshots group. `reference`
 * serializes as `"ref"` for the frontend.
 */
export type Snapshot = { ref: string; ts: number; sha: string; subject: string }
/**
 * One stash entry, newest (`stash@{0}`) first.
 */
export type StashEntry = { index: number; sha: string; branch: string | null; message: string }
/**
 * Result of a stash-conflict finalize step (`stash_conflict_abort` /
 * `stash_conflict_continue`). Deliberately the SAME shape as
 * `MergeResult`/`RebaseResult` (see `git_merge.rs`'s doc comment for why each
 * op module gets its own type rather than sharing one across module
 * boundaries): the shared Resolver's `OPS`/dispatch table treats every op's
 * result structurally (`.state`/`.conflictedFiles`/`.message`/`.backupRef`),
 * so a "stash" entry with this shape slots in exactly like the others.
 */
export type StashResolveResult = { ok: boolean; 
/**
 * "clean" | "conflict" | "error" (never "empty" — finalizing a stash
 * conflict is never a no-op).
 */
state: string; conflictedFiles: string[]; message: string; backupRef: string | null }
export type TagObject = { sha: string; name: string; tagger: PlumbingPerson | null; message: string; targetOid: string; targetKind: string }
/**
 * One entry inside a tree listing.
 */
export type TreeEntryRow = { name: string; 
/**
 * Octal file mode as git prints it, e.g. `"100644"`, `"100755"`,
 * `"040000"`, `"120000"` (symlink), `"160000"` (submodule/gitlink).
 */
mode: string; 
/**
 * `"blob"` | `"tree"` | `"commit"` (submodule) — whatever the entry's
 * object type resolves to.
 */
kind: string; oid: string }
export type TreeObject = { sha: string; entries: TreeEntryRow[] }
/**
 * Result of a global undo.
 */
export type UndoResult = { ok: boolean; message: string; restoredTo: string | null; sealed: string | null }
/**
 * One working-tree/index entry. `status` reuses `FileChange`'s vocabulary
 * (A/M/D/R/T) plus `"?"` for untracked (git's own porcelain symbol; distinct
 * from `"A"` so a brand-new-but-staged file and a not-yet-tracked file never
 * look the same).
 */
export type WorkdirEntry = { path: string; oldPath: string | null; status: string }
/**
 * Result of any working-tree mutation. Same `{ok, message}` contract as
 * `WriteResult`/`MergeResult`, extended with TWO different safety-net
 * channels (see this module's doc comment for which op populates which).
 */
export type WorkdirResult = { ok: boolean; message: string; 
/**
 * Non-empty only for a `stash_apply`/`stash_pop` left mid-conflict.
 */
conflictedFiles: string[]; 
/**
 * Safety-Manager ref snapshot (`commit`/`stash_*` only).
 */
backupRef: string | null; 
/**
 * Path to a saved pre-discard copy (`discard_file` only).
 */
backupPatch: string | null; 
/**
 * Ref pinning a DROPPED stash's own commit so it survives `git gc`
 * (`stash_drop` only). `safety::snapshot`'s `backup_ref` only ever tracks
 * `refs/heads/*` — never `refs/stash` — so it can't make a dropped stash
 * itself recoverable; this is the honest, separate recovery channel (see
 * `pin_dropped_stash`). Recover with `git stash apply <this ref>` (or
 * `git branch <name> <this ref>` to just inspect it).
 */
droppedStashRef: string | null }
/**
 * Full working-tree snapshot backing the pinned "Uncommitted changes" row.
 */
export type WorkdirStatus = { staged: WorkdirEntry[]; unstaged: WorkdirEntry[]; conflicted: number; branch: string | null; hasStash: boolean }
/**
 * Uniform result of a write command. `ok:false` carries git's stderr (trimmed)
 * or a validation/precondition message.
 */
export type WriteResult = { ok: boolean; message: string; 
/**
 * Backup ref sealed before the mutation (present on success), so the UI can
 * name the snapshot the user can Undo to. `None` when we never got to snapshot.
 */
backupRef: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
