// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Tauri command wrapper — see [`build_graph`].
 */
async loadGraph(path: string, limit: number | null) : Promise<Result<GraphData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_graph", { path, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: return the full message + real changed-file tree + diff hunks
 * for a single commit. Diffs the commit tree against its FIRST parent (empty
 * tree for a root commit; first parent for a merge). Read-only.
 */
async commitDetail(path: string, sha: string) : Promise<Result<CommitDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_detail", { path, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSnapshot(path: string) : Promise<Result<Snapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_snapshot", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSnapshots(path: string) : Promise<Result<Snapshot[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snapshots", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async undoLast(path: string) : Promise<Result<UndoResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_last", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: list local branches (+ ahead/behind vs upstream), remote
 * branches, and tags, plus the current branch shorthand. Read-only (git2).
 */
async listRefs(path: string) : Promise<Result<RefList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_refs", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a branch; when `checkout` is true, also switch to it (`git switch -c`).
 * `start_point` is an optional commit-ish; defaults to HEAD when omitted.
 * JS call: `invoke("create_branch", { path, name, startPoint?, checkout? })`.
 */
async createBranch(path: string, name: string, startPoint: string | null, checkout: boolean | null) : Promise<WriteResult> {
    return await TAURI_INVOKE("create_branch", { path, name, startPoint, checkout });
},
/**
 * Switch HEAD to an existing branch. Uses `git switch` (never touches
 * pathspecs, so no branch/path ambiguity). A dirty tree that would be
 * clobbered is surfaced as `ok:false` with git's message — we never force.
 * JS call: `invoke("checkout", { path, name })`.
 */
async checkout(path: string, name: string) : Promise<WriteResult> {
    return await TAURI_INVOKE("checkout", { path, name });
},
/**
 * Delete a branch. Refuses the current branch. `force=false` uses `git branch
 * -d` (refuses an unmerged branch -> surfaced as `ok:false`); `force=true` uses
 * `-D`. The deleted tip sha is included in the success message since M2a Undo
 * restores HEAD only (full-repo ref restore comes later).
 * JS call: `invoke("delete_branch", { path, name, force })`.
 */
async deleteBranch(path: string, name: string, force: boolean) : Promise<WriteResult> {
    return await TAURI_INVOKE("delete_branch", { path, name, force });
},
/**
 * Rename a branch. Uses `git branch -m` (NOT `-M`), so it refuses to clobber an
 * existing target. Works on the current branch (git updates the HEAD symref).
 * JS call: `invoke("rename_branch", { path, from, to })`.
 */
async renameBranch(path: string, from: string, to: string) : Promise<WriteResult> {
    return await TAURI_INVOKE("rename_branch", { path, from, to });
},
/**
 * Report the in-progress operation and the conflicted files (with all three
 * merge stages). Read-only. JS: `invoke("conflict_status", { path })`.
 */
async conflictStatus(path: string) : Promise<Result<ConflictStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conflict_status", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve one conflicted file by taking the whole `ours` or `theirs` side, then
 * staging it. Returns how many files are still unmerged so the UI can flip to
 * "Continue" when it reaches 0. JS: `invoke("resolve_conflict_file", { path,
 * file, side })` where `side` is `"ours"` or `"theirs"`.
 * 
 * No snapshot here — see the module doc: the enclosing op was snapshotted and
 * its `--abort` restores everything.
 */
async resolveConflictFile(path: string, file: string, side: string) : Promise<ResolveResult> {
    return await TAURI_INVOKE("resolve_conflict_file", { path, file, side });
},
/**
 * Cherry-pick `sha` onto the current branch (HEAD). Snapshots FIRST, then runs
 * `git cherry-pick [-x] --no-edit --end-of-options <sha>`. `record_origin`
 * (the `-x` toggle) appends "(cherry picked from commit …)" to the message.
 * 
 * A dirty working tree makes git refuse the pick — that surfaces as
 * `state:"error"` with git's own message; we never force. On a conflict this
 * resolves to `state:"conflict"` (repo left mid-pick for the resolver), NOT a
 * failure.
 * 
 * JS: `invoke("cherry_pick", { path, sha, recordOrigin? })`.
 */
async cherryPick(path: string, sha: string, recordOrigin: boolean | null) : Promise<PickResult> {
    return await TAURI_INVOKE("cherry_pick", { path, sha, recordOrigin });
},
/**
 * Continue an in-progress cherry-pick after the user resolved the conflict
 * (files were `git add`ed by the resolver). Runs `git cherry-pick --continue`
 * with `GIT_EDITOR=true` so it commits the resolution non-interactively.
 * 
 * Re-classifies the outcome: `clean` on success, `conflict` again if conflicts
 * remain unresolved, or `empty` if the resolution left no net change.
 * 
 * JS: `invoke("cherry_pick_continue", { path })`.
 */
async cherryPickContinue(path: string) : Promise<PickResult> {
    return await TAURI_INVOKE("cherry_pick_continue", { path });
},
/**
 * Abort an in-progress cherry-pick: `git cherry-pick --abort` restores the
 * pre-pick state. This is the escape hatch — it must ALWAYS be able to run, so
 * it deliberately does NOT take a snapshot (a snapshot failure must never block
 * the user's way out). Idempotent: "nothing in progress" is a benign success.
 * 
 * JS: `invoke("cherry_pick_abort", { path })`.
 */
async cherryPickAbort(path: string) : Promise<PickResult> {
    return await TAURI_INVOKE("cherry_pick_abort", { path });
},
/**
 * Start a bisect between a known-bad and one-or-more known-good commits.
 * Snapshots FIRST. JS: invoke("bisect_start", { path, bad, good: [sha,…] }).
 */
async bisectStart(path: string, bad: string, good: string[]) : Promise<BisectStatus> {
    return await TAURI_INVOKE("bisect_start", { path, bad, good });
},
/**
 * Mark the checked-out midpoint (HEAD) good/bad/skip. No snapshot.
 * JS: invoke("bisect_mark", { path, term }) where term ∈ {good,bad,skip}.
 */
async bisectMark(path: string, term: string) : Promise<BisectStatus> {
    return await TAURI_INVOKE("bisect_mark", { path, term });
},
/**
 * Read-only bisect status (also serves as `bisect log`). Never mutates.
 * JS: invoke("bisect_status", { path }).
 */
async bisectStatus(path: string) : Promise<BisectStatus> {
    return await TAURI_INVOKE("bisect_status", { path });
},
/**
 * End the bisect and restore the original HEAD/branch. Escape hatch: NO
 * snapshot; idempotent. JS: invoke("bisect_reset", { path }).
 */
async bisectReset(path: string) : Promise<BisectStatus> {
    return await TAURI_INVOKE("bisect_reset", { path });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BisectStatus = { ok: boolean; inProgress: boolean; current: CommitInfo | null; badRef: string | null; goodRefs: string[]; remainingRevs: number; estSteps: number; firstBad: CommitInfo | null; log: string[]; message: string; backupRef: string | null }
/**
 * Full payload for the M1 commit detail panel: message + real diff tree.
 */
export type CommitDetail = { sha: string; shortSha: string; subject: string; body: string; message: string; additions: number; deletions: number; filesChanged: number; truncated: boolean; fileTree: FileChange[] }
export type CommitInfo = { sha: string; subject: string }
/**
 * Per-commit metadata (one entry per row, row = index).
 */
export type CommitMeta = { sha: string; subject: string; an: Person; cm: Person; refs: RefChip[]; merge: boolean }
/**
 * One conflicted file, with the three merge stages as text.
 * 
 * `base` = stage 1 (common ancestor), `ours` = stage 2 (HEAD / current branch),
 * `theirs` = stage 3 (the incoming commit — during a cherry-pick, the picked
 * commit). A side that is **absent** (e.g. add/add has no base; delete/modify
 * has no ours or theirs) is the empty string; a **binary** side is the marker
 * `"‹binary›"`. Each side is UTF-8-lossy and capped to [`CAP_LINES`].
 */
export type ConflictFile = { path: string; ours: string; base: string; theirs: string }
/**
 * Result of [`conflict_status`]. `op` is one of
 * `"cherry-pick" | "merge" | "rebase" | "revert" | "none"`. `in_progress` is
 * true whenever a sequencer op is underway **or** there are unmerged files —
 * so once every file is resolved (`files` empty) but the cherry-pick has not
 * been continued yet, `in_progress` stays true and the UI can offer Continue.
 */
export type ConflictStatus = { inProgress: boolean; op: string; files: ConflictFile[] }
/**
 * One hunk within a file patch. `header` is the `@@ -a,b +c,d @@ ...` line.
 */
export type DiffHunkRow = { header: string; lines: DiffLineRow[] }
/**
 * One line inside a diff hunk. `old_no`/`new_no` are the 1-based line numbers
 * on each side; the added side has `old_no == None`, the deleted side
 * `new_no == None`, context lines carry both. `text` is the raw line content
 * with any trailing CR/LF stripped — the frontend HTML-escapes it.
 */
export type DiffLineRow = { kind: string; oldNo: number | null; newNo: number | null; text: string }
/**
 * One changed file: its status, per-file stats, and hunks. `hunks` is empty
 * for a binary file (`binary == true`) or when the file was capped
 * (`truncated == true`). `old_path` is set only for renames/copies.
 */
export type FileChange = { path: string; oldPath: string | null; status: string; additions: number; deletions: number; binary: boolean; truncated: boolean; lang: string; hunks: DiffHunkRow[] }
/**
 * The full graph payload. Rows are in reverse-chronological/topological order
 * (child before parent). `lane`/`color`/`merge` are one-per-row.
 * 
 * Edges are stored CSR-style: `gap g` is the band between row g and row g+1;
 * `gapStart[g]..gapStart[g+1]` indexes into `gapTop`/`gapBot`/`gapColor`, each
 * entry a line segment {top lane @row g, bottom lane @row g+1, colour index}.
 */
export type GraphData = { n: number; lane: number[]; color: number[]; merge: number[]; gapStart: number[]; gapTop: number[]; gapBot: number[]; gapColor: number[]; rows: CommitMeta[]; ncol: number; laneCount: number; layoutMs: number; readMs: number }
/**
 * A local branch row for the data-driven sidebar. `ahead`/`behind` are relative
 * to the branch's configured upstream, or `None` when it has no upstream.
 */
export type LocalBranch = { name: string; sha: string; ahead: number | null; behind: number | null }
/**
 * One author/committer identity. `t` is a unix timestamp; the frontend formats it.
 */
export type Person = { n: string; e: string; t: number }
/**
 * Result of any cherry-pick step (initial / continue / abort). Serializes
 * camelCase: `conflictedFiles`, `backupRef`.
 */
export type PickResult = { ok: boolean; 
/**
 * "clean" | "conflict" | "empty" | "error"
 */
state: string; 
/**
 * Repo-relative paths with unmerged entries — non-empty only when
 * `state == "conflict"`.
 */
conflictedFiles: string[]; message: string; 
/**
 * Pre-op safety snapshot ref (present when we snapshotted before mutating),
 * so the UI can name the snapshot the user can Undo to.
 */
backupRef: string | null }
/**
 * A ref chip pointing at a commit. `t` is one of: head | branch | remote | tag.
 */
export type RefChip = { n: string; t: string }
/**
 * Everything the sidebar needs. `head` is the current branch shorthand, or
 * `None` when HEAD is detached or unborn.
 */
export type RefList = { head: string | null; locals: LocalBranch[]; remotes: SimpleRef[]; tags: SimpleRef[] }
/**
 * Result of [`resolve_conflict_file`]. `remaining` is the count of files still
 * unmerged after this resolution (0 means the tree is ready to Continue).
 */
export type ResolveResult = { ok: boolean; remaining: number; message: string }
/**
 * A remote-tracking branch or a tag: just a name and the commit it resolves to.
 */
export type SimpleRef = { name: string; sha: string }
/**
 * One backup snapshot, as shown in the ribbon / Snapshots group. `reference`
 * serializes as `"ref"` for the frontend.
 */
export type Snapshot = { ref: string; ts: number; sha: string; subject: string }
/**
 * Result of a global undo.
 */
export type UndoResult = { ok: boolean; message: string; restoredTo: string | null; sealed: string | null }
/**
 * Uniform result of a write command. `ok:false` carries git's stderr (trimmed)
 * or a validation/precondition message.
 */
export type WriteResult = { ok: boolean; message: string; 
/**
 * Backup ref sealed before the mutation (present on success), so the UI can
 * name the snapshot the user can Undo to. `None` when we never got to snapshot.
 */
backupRef: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
