// Emits src-tauri/src/keymap_generated.rs from src/keymap/accelerators.ts.
// Run: `pnpm keymap:gen`. CI runs it then `git diff --exit-code`.
//
// Imports ONLY accelerators.ts and chord.ts. Both have zero app imports (see
// src/keymap/boundary.test.ts, which asserts it) and explicit .ts extensions,
// which is what `node --experimental-strip-types` needs. bindings.ts is
// deliberately NOT read here: it reaches guards.ts -> legacy/bridge ->
// legacy/main.ts, a canvas app that boots on import.
import { writeFileSync } from "node:fs";
import { ACCELERATORS } from "../src/keymap/accelerators.ts";
import { parseChord, toAccelerator } from "../src/keymap/chord.ts";

const HEADER = `// @generated by \`pnpm keymap:gen\` from src/keymap/accelerators.ts — DO NOT EDIT.
//
// Only menu items with a NATIVE accelerator appear here. An item with no entry
// gets an unmodified builder from menu.rs's \`mk\` helper, byte-identical to a
// plain \`.build(app)?\` — so ABSENCE is the default and PRESENCE is the opt-in.
// That is what keeps menu.rs's three documented omissions (:68-71, :91-93,
// :118-121) deliberate rather than "someone forgot".
`;

const rows = Object.entries(ACCELERATORS)
  .map(([id, spec]) => [id, toAccelerator(parseChord(spec))] as const)
  .sort((a, b) => (a[0] < b[0] ? -1 : 1));

const w = Math.max(...rows.map((r) => r[0].length)) + 4;
const body = rows.map(([id, a]) => `    (${`"${id}",`.padEnd(w)}"${a}"),`).join("\n");

const out = `${HEADER}
/// (menu item id, muda accelerator). Sorted by id for a stable diff.
pub const ACCELERATORS: &[(&str, &str)] = &[
${body}
];

/// Accelerator for a menu item id, or None when the item deliberately has none.
pub fn accel(id: &str) -> Option<&'static str> {
    ACCELERATORS.iter().find(|(k, _)| *k == id).map(|(_, a)| *a)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Structural, not a muda parse: tauri 2.11 takes accelerators as plain
    // \`AsRef<str>\` and re-exports no \`Accelerator\` type, so muda's parser is
    // unreachable from here. This still catches every realistic codegen
    // failure \u2014 an empty string, a stray separator, a dropped key token, an
    // unknown modifier \u2014 which is what a generated table can actually get wrong.
    #[test]
    fn every_accelerator_is_well_formed() {
        const MODS: [&str; 3] = ["CmdOrCtrl", "Shift", "Alt"];
        for (id, a) in ACCELERATORS {
            assert!(!a.is_empty(), "{id} has an empty accelerator");
            let parts: Vec<&str> = a.split('+').collect();
            assert!(parts.len() >= 2, "{id}: {a:?} has no modifier");
            assert!(
                parts.iter().all(|p| !p.is_empty()),
                "{id}: {a:?} has an empty segment"
            );
            let (key, mods) = parts.split_last().unwrap();
            assert!(
                mods.iter().all(|m| MODS.contains(m)),
                "{id}: {a:?} has an unknown modifier"
            );
            assert!(
                !MODS.contains(key),
                "{id}: {a:?} ends in a modifier, not a key"
            );
        }
    }

    #[test]
    fn ids_are_unique_and_sorted() {
        let mut ids: Vec<&str> = ACCELERATORS.iter().map(|(k, _)| *k).collect();
        let n = ids.len();
        ids.sort_unstable();
        ids.dedup();
        assert_eq!(ids.len(), n, "duplicate menu id in ACCELERATORS");
        assert!(ACCELERATORS.windows(2).all(|w| w[0].0 < w[1].0), "ACCELERATORS is not sorted");
    }
}
`;

writeFileSync(new URL("../src-tauri/src/keymap_generated.rs", import.meta.url), out);
console.log(`keymap:gen wrote ${rows.length} accelerators`);
