//! Remote CONFIG CRUD: add / rename / set-url / remove / list. NOT to be
//! confused with git_remote.rs (fetch/pull/push/push_tag — actual NETWORK
//! sync). Lives in its own sibling module rather than appended to
//! git_remote.rs, for the same reason push_tag lives IN git_remote.rs rather
//! than git_tag.rs (see that module's own doc comment): module boundaries in
//! this codebase are drawn by "which operation needs which existing
//! module's conventions", not by "same noun as an existing file". Fetch/
//! pull/push/push_tag all share git_remote.rs's actual reason to exist —
//! they talk to a real remote over the network, can be rejected by it, and
//! (per that module's doc) NEVER force. add/rename/set-url/remove/list need
//! NONE of that: no network call, no "rejection", no force-vs-no-force
//! question — they only ever rewrite this repo's OWN `.git/config` (or, for
//! `list`, just read it). That's exactly git_tag.rs's own shape (small,
//! self-contained, local-only CRUD, no network, no snapshot) — not
//! git_remote.rs's — so this gets its own module rather than growing
//! git_remote.rs into two unrelated jobs glued together by a shared noun.
//!
//! Reuses `git_remote::RemoteResult` verbatim as the write return type
//! (rather than a FOURTH near-identical `{ok, message, backup_ref}` copy) —
//! exactly how git_tag.rs reuses git_write::WriteResult. RemoteResult's own
//! `ok()`/`err()` are private to git_remote.rs, so — mirroring git_tag.rs's
//! own `ok_result`/`err_result` pattern for WriteResult — this module builds
//! the struct literal directly via its own small wrappers below (all 3
//! fields are `pub`). Keeps its own private run_git/git_error_message/
//! validate_remote_name copies rather than importing git_remote.rs's
//! (private to that module anyway) — this codebase's established
//! per-module-copy convention (see git_remote.rs's own doc comment).
//!
//! No Safety Manager snapshot anywhere here: none of these mutate local
//! HEAD, a local branch, or the working tree — only a remote's config entry
//! (and, for rename/remove, that remote's OWN refs/remotes/<name>/*
//! tracking refs) — so there is nothing for Undo to protect, identical to
//! plain fetch/push's own no-snapshot rationale in git_remote.rs's module
//! doc. `remove_remote` really does delete refs/remotes/<name>/* (real git
//! behavior) with no pin/backup net — this is deliberate, not an oversight:
//! unlike a deleted branch/tag tip, a remote's tracking refs are trivially
//! regenerated by `fetch` the moment the remote (or an equivalent one)
//! exists again, so there is nothing irreplaceable a pin would protect.
//!
//! Every write command passes `--end-of-options` before `<name>`/`<url>`
//! (matching git_remote.rs's own fetch/push_tag posture: `git remote add
//! --end-of-options -weird <url>` adds a remote literally named "-weird"
//! rather than misparsing it as a flag) AND separately refuses a leading `-`
//! itself via validate_remote_name/validate_remote_url, for the same
//! "defense in depth, clearer message" reasoning git_write.rs's
//! validate_branch_name doc gives.
//!
//! Duplicate-name / not-found / rename-onto-an-existing-name errors are
//! passed through from git's own stderr VERBATIM, never wrapped — matching
//! every other write command in this codebase (fetch/pull/push/push_tag/
//! create_branch/delete_branch/rename_branch/create_tag/delete_tag all do
//! the identical "surface git's own message" thing, zero exceptions). e.g.
//! `git remote add` on a name that already exists -> "error: remote origin
//! already exists." — already a clear message; wrapping it would only risk
//! drifting from a future git wording change for no benefit. Likewise:
//! set-url/rename/remove on an unknown name -> "error: No such remote
//! 'x'"/"error: No such remote: 'x'"; rename onto an existing name ->
//! "error: remote y already exists."

use std::process::Command;

use serde::Serialize;

use crate::git_remote::RemoteResult;

// ---------------------------------------------------------------------------
// RemoteResult constructors (RemoteResult's own `ok`/`err` are private to
// git_remote.rs — mirrors git_tag.rs's identical `ok_result`/`err_result`
// pattern for WriteResult; see module doc comment).
// ---------------------------------------------------------------------------

fn ok_result(message: impl Into<String>) -> RemoteResult {
    RemoteResult { ok: true, message: message.into(), backup_ref: None }
}
fn err_result(message: impl Into<String>) -> RemoteResult {
    RemoteResult { ok: false, message: message.into(), backup_ref: None }
}

// ---------------------------------------------------------------------------
// Payload: a CONFIGURED remote (this remote's own config entry: name + fetch
// url + optional distinct push url). DISTINCT from git_write::SimpleRef
// (remote-TRACKING BRANCHES, refs/remotes/*) — do not conflate the two.
// ---------------------------------------------------------------------------

#[derive(Serialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct RemoteEntry {
    pub name: String,
    pub url: String,
    /// `Some` only when `remote.<name>.pushurl` is configured AND differs
    /// from `url` — git allows setting pushurl equal to the fetch url,
    /// which isn't meaningfully "distinct" and would just be a confusing
    /// second identical-looking row in the UI, so that case collapses to
    /// `None`, same as "no pushurl configured at all".
    pub push_url: Option<String>,
}

// ---------------------------------------------------------------------------
// git CLI runner (own copy — see module doc comment)
// ---------------------------------------------------------------------------

struct GitOut {
    ok: bool,
    code: Option<i32>,
    stdout: String,
    stderr: String,
}

fn run_git(path: &str, args: &[&str]) -> Result<GitOut, String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(path)
        .args(args)
        .output()
        .map_err(|e| format!("Could not run git: {e}"))?;
    Ok(GitOut {
        ok: output.status.success(),
        code: output.status.code(),
        stdout: String::from_utf8_lossy(&output.stdout).trim().to_string(),
        stderr: String::from_utf8_lossy(&output.stderr).trim().to_string(),
    })
}

fn git_error_message(out: &GitOut) -> String {
    if !out.stderr.is_empty() {
        out.stderr.clone()
    } else if !out.stdout.is_empty() {
        out.stdout.clone()
    } else {
        format!("git exited with status {:?}", out.code)
    }
}

// ---------------------------------------------------------------------------
// Validation (own copies — see module doc comment)
// ---------------------------------------------------------------------------

/// Byte-identical copy of git_remote.rs's `validate_remote_name`
/// (per-module-copy convention).
fn validate_remote_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("Remote name is empty.".into());
    }
    if name.starts_with('-') {
        return Err(format!("Refusing a remote name that looks like a flag: {name:?}"));
    }
    if name.chars().any(|c| c.is_control() || c == ' ') {
        return Err(format!("Remote name has an illegal whitespace/control character: {name:?}"));
    }
    Ok(())
}

/// Lighter guard for the URL value — same shape as git_write.rs's private
/// `validate_revision`/git_tag.rs's `validate_revision`: only stops
/// flag-injection and control chars, `--end-of-options` covers the rest at
/// the CLI boundary. URLs legitimately contain characters a remote NAME
/// never could (`:`, `//`, `@`, `~`), so this is deliberately much lighter
/// than validate_remote_name.
fn validate_remote_url(url: &str) -> Result<(), String> {
    if url.is_empty() {
        return Err("Remote URL is empty.".into());
    }
    if url.starts_with('-') {
        return Err(format!("Refusing a URL that looks like a flag: {url:?}"));
    }
    if url.chars().any(|c| c.is_control()) {
        return Err("Remote URL has a control character.".into());
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Read: list configured remotes (git2) — feeds the Manage Remotes dialog
// ---------------------------------------------------------------------------

/// List every configured remote (name + fetch url + distinct push url, if
/// any). Read-only (git2), mirrors list_refs/submodule_status's own
/// git2-for-reads + `Result<T, String>` convention.
/// JS call: `invoke("list_remotes", { path })`.
///
/// BUG FIX: was a plain (non-async) `fn` — per `blocking.rs`'s doc comment,
/// that runs INLINE on Tauri's main thread. This opens the repository and
/// walks its configured remotes via git2, which for a WSL/UNC-bridged repo
/// can be the same kind of multi-second-or-worse stall `dashboard_repo_status`
/// and `workdir_status` were already fixed for, freezing the entire app
/// window for as long as it takes. `async fn` + `run_blocking` moves the work
/// onto Tauri's blocking-task thread pool, matching that established pattern.
#[tauri::command]
#[specta::specta]
pub async fn list_remotes(path: String) -> Result<Vec<RemoteEntry>, String> {
    crate::blocking::run_blocking(move || list_remotes_inner(&path).map_err(|e| e.message().to_string())).await
}

fn list_remotes_inner(path: &str) -> Result<Vec<RemoteEntry>, git2::Error> {
    let repo = crate::trust::open_repo(path)?;
    let names = repo.remotes()?;
    let mut out = Vec::new();
    for name in names.iter().flatten() {
        // non-UTF8 name -> skip, same "skip, don't crash" rule list_refs
        // already applies to non-UTF8 branch names.
        let remote = repo.find_remote(name)?;
        let url = remote.url().unwrap_or("").to_string();
        let push_url = remote.pushurl().map(|p| p.to_string()).filter(|p| p != &url);
        out.push(RemoteEntry { name: name.to_string(), url, push_url });
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

// ---------------------------------------------------------------------------
// Writes: no git2, no snapshot (see module doc comment) — validate, then a
// single --end-of-options-guarded git CLI call, git's own message passed
// through verbatim on failure. Same "no git2 needed, an invalid path
// surfaces git's own error just as clearly" reasoning as plain fetch().
// ---------------------------------------------------------------------------

/// Add a new remote (`git remote add`). Refuses a duplicate name via git's
/// own error rather than a pre-check (see module doc comment for why).
/// JS call: `invoke("add_remote", { path, name, url })`.
///
/// BUG FIX: was a plain (non-async) `fn` — it shells out to a real `git`
/// subprocess (`Command::new("git")`) and blocks waiting for it to exit,
/// which ran inline on Tauri's main thread and froze the entire app window
/// for as long as that subprocess took, not just this dialog. `async fn` +
/// `run_blocking` moves the wait onto Tauri's blocking-task thread pool,
/// matching `workdir_status`'s own established fix for the identical class
/// of stall.
#[tauri::command]
#[specta::specta]
pub async fn add_remote(path: String, name: String, url: String) -> RemoteResult {
    crate::blocking::run_blocking(move || {
        if let Err(e) = validate_remote_name(&name) {
            return err_result(e);
        }
        if let Err(e) = validate_remote_url(&url) {
            return err_result(e);
        }
        match run_git(&path, &["remote", "add", "--end-of-options", &name, &url]) {
            Ok(out) if out.ok => ok_result(format!("Added remote {name}.")),
            // e.g. "error: remote origin already exists."
            Ok(out) => err_result(git_error_message(&out)),
            Err(e) => err_result(e),
        }
    })
    .await
}

/// Rename a remote (`git remote rename`). Validates BOTH names. Real git
/// behavior: also renames every refs/remotes/<old>/* tracking ref to
/// refs/remotes/<new>/* — nothing extra needed here for that.
/// JS call: `invoke("rename_remote", { path, oldName, newName })`.
///
/// BUG FIX: was a plain (non-async) `fn` — same as `add_remote` above, it
/// shells out to `git remote rename` and blocks Tauri's main thread on that
/// subprocess (which, for a remote with many tracking refs to rewrite, is
/// not instant) for as long as it runs. `async fn` + `run_blocking` moves the
/// wait onto Tauri's blocking-task thread pool.
#[tauri::command]
#[specta::specta]
pub async fn rename_remote(path: String, old_name: String, new_name: String) -> RemoteResult {
    crate::blocking::run_blocking(move || {
        if let Err(e) = validate_remote_name(&old_name) {
            return err_result(e);
        }
        if let Err(e) = validate_remote_name(&new_name) {
            return err_result(e);
        }
        match run_git(&path, &["remote", "rename", "--end-of-options", &old_name, &new_name]) {
            Ok(out) if out.ok => ok_result(format!("Renamed remote {old_name} \u{2192} {new_name}.")),
            // e.g. "error: No such remote: 'x'" or "error: remote y already exists."
            Ok(out) => err_result(git_error_message(&out)),
            Err(e) => err_result(e),
        }
    })
    .await
}

/// Change a remote's fetch URL (`git remote set-url`) — the "edit" half of
/// add/edit/rename/remove; there is no separate edit_remote command since
/// editing IS changing the URL (or renaming, via rename_remote above).
/// JS call: `invoke("set_remote_url", { path, name, url })`.
///
/// BUG FIX: was a plain (non-async) `fn` — same as `add_remote` above, it
/// shells out to `git remote set-url` and blocks Tauri's main thread on that
/// subprocess for as long as it runs, freezing the whole app window rather
/// than just this dialog. `async fn` + `run_blocking` moves the wait onto
/// Tauri's blocking-task thread pool.
#[tauri::command]
#[specta::specta]
pub async fn set_remote_url(path: String, name: String, url: String) -> RemoteResult {
    crate::blocking::run_blocking(move || {
        if let Err(e) = validate_remote_name(&name) {
            return err_result(e);
        }
        if let Err(e) = validate_remote_url(&url) {
            return err_result(e);
        }
        match run_git(&path, &["remote", "set-url", "--end-of-options", &name, &url]) {
            Ok(out) if out.ok => ok_result(format!("Updated {name}'s URL.")),
            // e.g. "error: No such remote 'x'"
            Ok(out) => err_result(git_error_message(&out)),
            Err(e) => err_result(e),
        }
    })
    .await
}

/// Remove a remote entirely (`git remote remove`) — deletes its config
/// entry AND every refs/remotes/<name>/* tracking ref (real git behavior,
/// not a bug to work around). No snapshot/pin: see module doc comment for
/// why there is deliberately no undo net here — the frontend MUST confirm
/// before calling this.
/// JS call: `invoke("remove_remote", { path, name })`.
///
/// BUG FIX: was a plain (non-async) `fn` — same as `add_remote` above, it
/// shells out to `git remote remove` (which also has to delete every one of
/// that remote's tracking refs) and blocks Tauri's main thread on that
/// subprocess for as long as it runs. `async fn` + `run_blocking` moves the
/// wait onto Tauri's blocking-task thread pool.
#[tauri::command]
#[specta::specta]
pub async fn remove_remote(path: String, name: String) -> RemoteResult {
    crate::blocking::run_blocking(move || {
        if let Err(e) = validate_remote_name(&name) {
            return err_result(e);
        }
        match run_git(&path, &["remote", "remove", "--end-of-options", &name]) {
            Ok(out) if out.ok => ok_result(format!("Removed remote {name}.")),
            // e.g. "error: No such remote: 'x'"
            Ok(out) => err_result(git_error_message(&out)),
            Err(e) => err_result(e),
        }
    })
    .await
}
